version: "3.6"
services:
  restapi:
    image: backend
    build: .
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"
    entrypoint: ["python3", "main.py"]
    networks:
      - vkr_net
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=vkr_backend_db
      - POSTGRES_DB=vkr_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - vkr_net
  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - '8080:7070'
    networks:
      - vkr_net
  minio:
    image: minio/minio
    command: server /data
    ports:
      - '9000:9000'
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=hello_vkr
    restart: always
    volumes:
      - ./minio-data:/data
    networks:
      - vkr_net
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
networks:
  vkr_net:
    external: true